config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  devise_for :users
  resources :users
  resources :trips
  resources :expenses
  resources :usertrip
  resources :participants
  root to: "home#index"

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :users, :through => :usertrips
  has_many :expenses
  has_many :participants
  has_many :usertrips 
  belongs_to :country
  belongs_to :currency
  

  def total 
    self.expenses.reduce(0) do |sum, expense|
      sum+=expense.amount
    end
  end
  
  def split
    total/participants.length 
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  def index
    @trips = Trip.all
  end

 
  def show
    @trip = Trip.find(params[:id])
    @total = @trip.total
  end


  def new
    @trip = Trip.new
  end


  def edit
  @trip = Trip.find(params[:id])
  end

  def create
    @trip = Trip.new(trip_params) 
    @trip.users<<current_user
    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'New trip created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @trip = Trip.find(params[:id])
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Your trip has been updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Your trip has been deleted.' }
      format.json { head :no_content }
    end
  end

    

    private
      def set_trip
        @trip = Trip.find(params[:id])
      end
      
      def trip_params
        params.require(:trip).permit(:tripname, :country_id, :currency_id, :participant_id, :expense_id)
      end
end

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
<% if @trip.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

  <ul>
    <% @trip.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :tripname %>
  <%= f.text_field :tripname %>
</div>

<div class="currency">
  <%= f.label :currency, :class=> "selector" %>
  <%= f.collection_select :currency_id, Currency.all.order(:name),:id,:name %>
</div>

<div class="country">
  <%= f.label :country, :class=> "selector" %>
  <%= f.collection_select :country_id, Country.all.order(:name),:id,:name %>
</div>


<%#= link_to 'Add Participant', new_participant_path, :class=> "btn" %>

<div class="actions">
  <%= f.submit "Save", :class=> "btn" %>
</div>
<%#= link_to 'New Expense', new_expense_path, :class=> "btn" %>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form' %>

<%= link_to 'Cancel', @trip, :class=> "btn text" %>
<%= link_to 'Delete', @trip, method: :delete, data: { confirm: 'Are you sure?' }, :class=> "btn error" %>

app/views/trips/index.html.erb
<div class="card">
<h1>All Trips</h1>

<p id="notice"><%= notice %></p>

<ul class="list trips collapse">
  
  <% @trips.reverse_each do |trip| %>
      <li>
        
        <%= link_to (trip) do %>
          <h3><%= trip.tripname %></h3>
          <small>
            <div><span class="icon-small icon-flag"></span><%= trip.country.try (:name) %></div>
            <div><span class="icon-small icon-coin-pound"></span><%= trip.currency.try (:name) %>
            </div>
            <span class="icon-keyboard_arrow_right"></span>
          </small>
          <div class="participants-count"><span class="icon-person"></span><%= trip.participants.length %></div>
        <% end %>
      
      </li>
    <% end %>
  </ul>

<%= link_to 'New Trip', new_trip_path, :class => 'btn' %>
</div>

app/views/trips/new.html.erb
<h1>Create New Trip</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path, :class=> "btn text"  %>

app/views/trips/show.html.erb
<div class="trip-wrapper">
<div class="trip-info">
  <header class="trip-header">
    <div class="black-fade"></div>
    <img id="trip-header" class="trip-image" src="//placehold.it/400x200?text=No+image+available" alt="" />

    <%= link_to trips_path, :class=> "btn secondary" do %>
    <span class="icon-navigate_before"></span> All Trips
    <% end %>

    <h1 class="trip-name">
      <%= @trip.tripname %><%= link_to edit_trip_path(@trip), :class=> "btn" do %>
      <span class="icon-edit"></span>
      <% end %>
    </h1>

    <div class="trip-meta">
      <span class="country">
        <span class="icon-flag"></span><%= @trip.country.try (:name) %>
      </span>
      <span class="currency">
        <span class="icon-coin-pound"></span><%= @trip.currency.try (:name) %>
      </span>
    </div>

  </header>
</div>

<p id="notice"><%= notice %></p>

<div class="trip-content">
  <section class="trip-participants">
    <h2>Trip Participants
      <%= link_to new_participant_path(trip_id: @trip.id), :class=> "btn" do %>
        <span class="icon-add"> Add</span>
      <% end %></h2>
     

    
    <% if @trip.participants.length > 0 %>
    <ul class="collapse">
      <% @trip.participants.each do |participant| %>
        <%= link_to edit_participant_path(participant) do %>
          <li>
            <%= participant.name %>
            <small>
            <%= participant.email %>
            </small>
          </li>
        <% end %>
      <% end %>
    </ul>
    <% else %>
      <div class="empty-state">
        <span class="icon-person"></span>
        <p>No Participants Added</p> 
      </div>
    <% end %>
  </section>

  <hr class="fancy"/>

  <section class="trip-expenses">
    <h2>Trip Expenses  <%= link_to new_expense_path(trip_id: @trip.id), :class=> "btn" do %>
        <span class="icon-add"> New</span>
      <% end %></h2>
     

    
    <% if @trip.expenses.length > 0 %>
    <ul class="collapse">
      <% @trip.expenses.each do |expense| %>
        <%= link_to (expense) do %>
        <li>
          <%= expense.name %>
          <strong>$ <%= expense.amount %></strong>
          <small>
          <%= expense.description %>
          </small>
        </li>
        <% end %>
      <% end %>
      </ul>
    <% else %>
      <div class="empty-state">
          <span class="icon-receipt"></span>
          <p>No Expenses Created</p> 
      </div>
    <% end %>
  </section>

  <% if @trip.participants.length > 0 && @trip.expenses.length > 0 %>
  <hr class="fancy"/>
  <section class="trip-expenses clearfix">
    <h2>Total <span class="total">$ <%= @total %></span></h2>
    <div class="per-person">
      <small>Amount per person</small>
        $ <%= @trip.split %> 
      <% total / participants.length rescue 0 %>
    </div>
  </section>
  <% end %>
</div> 