config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  devise_for :users
  resources :users
  resources :trips
  resources :expenses
  resources :usertrip
  resources :participants
  root to: "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :trips, :through => :usertrips
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
  has_many :expenses
  has_many :usertrips
  # has_many :friendships
  # has_many :friends, :through => :friendships
  # has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  # has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  has_many :friends, :through => :friendships
  has_many :requested_friends, :through => :friendships, :source => :friend
  has_many :pending_friends, :through => :friendships, :source => :friend
  has_many :friendships, :dependent => :destroy


  # has_many :feedbacks, :through => :passenger

  # before_create :set_default_role
  
  # def human_readable_date
  #   trip_date.strftime('%A %B %d %Y')
  # end

  def human_readable_time
    starting_time.strftime('%A %B %d %Y, %H:%M')
  end

  
  def role?(role_to_compare_to)
    role_to_compare_to.to_s == self.role.to_s
  end

  # def set_default_role
  #   self.role = "user" unless role
  # end 

  # def role (role_to_compare)
  #   self.role.to_s == role_to_compare.to_s
  # end

  def mailboxer_name
    self.name
  end

  def mailboxer_email(object)

   if object.class==Mailboxer::Notification
     return nil
      else
        email
   end
 end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

 
  def index
    @users = User.all
  end

 
  def show
  @user = User.find(params[:id])

  end


  def new
    @user = User.new
  end

 
  def edit
  end


  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :role, :created_at, :updated_at)
    end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

    <div class="field">
      <%= f.label :email %>
      <%= f.email_field :email, autofocus: true %>
    </div>

    <div class="field">
      <%= f.label :password %>
      <% if @minimum_password_length %>
      <small>(<%= @minimum_password_length %> characters minimum)</small>
      <% end %>
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

  <div class="actions">
    <%= f.submit :class=> "btn" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Role</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.role %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'add as friend', new_friendship_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Add Friend", users_path %>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
  <% if user_signed_in? %>
  <% unless @user == current_user || current_user.requested_friends.include?(@user) || current_user.friends.include?(@user) || current_user.pending_friends.include?(@user) %>
  <% form_for(:friendship, :url => user_friends_path(:user_id => current_user.id, :friend_id => @user.id)) do |f| %>
  <%= submit_tag "Add to My Friends" %>
<% end %>
<% end %>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @user.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @user.updated_at %>
</p>

<h2>Friends</h2>
<ul>
  <% for friendship in @user.friendships %>
    <li>
      <%=h friendship.friend.username %>
      (<%= link_to "remove", friendship, :method => :delete %>)
    </li>
  <% end %>
</ul>

<p><%= link_to "Find Friends", users_path %></p>
<!-- 
<h2>Friended by Users</h2>
<ul>
  <%# for user in @user.friend %>
    <li><%#=h user.username %></li>
  <%# end %>
</ul> -->


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>