config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  devise_for :users
  resources :users
  resources :trips
  resources :expenses
  resources :usertrip
  resources :participants
  root to: "home#index"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <h2>My Recent Trips</h2>

  <ul class="list trips collapse">
  <% current_user.trips[3..-1].reverse_each do |trip| %>
    <li>
      
      <%= link_to (trip) do %>
        <h3><%= trip.tripname %></h3>
        <small>
          <div><span class="icon-small icon-flag"></span><%= trip.country.try (:name) %></div>
          <div><span class="icon-small icon-coin-pound"></span><%= trip.currency.try (:name) %>
          </div>
          <span class="icon-keyboard_arrow_right"></span>
        </small>
          <div class="participants-count"><span class="icon-person"></span><%= trip.participants.length %></div>
      <% end %>
    
    </li>
  <% end %>
  </ul>

  <%= link_to 'Create new trip', new_trip_path, :class=> "btn" %>
  <hr class="fancy"/>
  <%= link_to 'View my Expenses', expenses_path, :class=> "btn secondary" %>
<% else %>
  
  <section class="hero">
    <h1>Welcome to ExpenseShare</h1>
    <h2>Keep a track of your expenses instantly</h2>  

    <%= link_to 'Get started', new_user_registration_path, :class=> "btn" %>
  </section>
  

  <div class="padded">
    <div class="wrapper-inner">
      <ul class="col_3 col collapse">
        <li>
          <h3>Share Expenses</h3>
          <%= image_tag("skii.jpg", :alt=>"Skiers") %>
          <p>Easy splitting of group expenses. The simplest way to calculate who owes what. Expenseez takes the trouble out of sharing expenses – with friends, with roommates, with anyone.</p>
        </li>
        <li>
          <h3>Manage Debts</h3>
          <%= image_tag("money.jpg", :alt => "Expense") %>
          <p>Smartly manage debts between friends. Expenseez keeps a running total over time, so you can pay each other back in one big payment, instead of a bunch of small ones.</p>
        </li>
        <li>
          <h3>Mobile Solution</h3>
          <%= image_tag("mobile.jpg", :alt => "Mobile") %>
          <p>No need to save the receipt! With mobile apps iPhone and Android, you can add expenses as soon as they happen. Get a picture of your receipt and have it saved in your trip.</p>
        </li>
      </ul>
    </div>
  </div>

<% end %>