config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  devise_for :users
  resources :users
  resources :trips
  resources :expenses
  resources :usertrip
  resources :participants
  root to: "home#index"

end

app/models/usertrip.rb
class Usertrip < ActiveRecord::Base
  belongs_to :user
  belongs_to :trip
  # has_many :participants


end

app/controllers/usertrips_controller.rb
class UserTripsController < ApplicationController
  before_action :set_usertrip, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!
  
  def index
    @usertrips = UserTrip.all
  end

  def show
  end


  def new
    @usertrip = UserTrip.new
  end


  def edit
  end

  def create
    @usertrip = UserTrip.new(user_trip_params)

    respond_to do |format|
      if @usertrip.save
        format.html { redirect_to @usertrip, notice: 'User trip was successfully created.' }
        format.json { render :show, status: :created, location: @usertrip }
      else
        format.html { render :new }
        format.json { render json: @usertrip.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @usertrip.update(usertrip_params)
        format.html { redirect_to @usertrip, notice: 'User trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @usertrip }
      else
        format.html { render :edit }
        format.json { render json: @usertrip.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @usertrip.destroy
    respond_to do |format|
      format.html { redirect_to usertrips_url, notice: 'User trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_usertrip
      @usertrip = UserTrip.find(params[:id])
    end

    def usertrip_params
      params.require(:usertrip).permit(:user_id, :trip_id)
    end
end

app/views/usertrips/_form.html.erb
<%= form_for(@usertrip) do |f| %>
  <% if @usertrip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usertrip.errors.count, "error") %> prohibited this usertrip from being saved:</h2>

      <ul>
      <% @usertrip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :trip_id %><br>
    <%= f.number_field :trip_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usertrips/edit.html.erb
<h1>Editing User Trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @usertrip %> |
<%= link_to 'Back', usertrips_path %>

app/views/usertrips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Trips</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Trip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usertrips.each do |usertrip| %>
      <tr>
        <td><%= usertrip.user_id %></td>
        <td><%= usertrip.trip_id %></td>
        <td><%= link_to 'Show', usertrip %></td>
        <td><%= link_to 'Edit', edit_usertrip_path(user_trip) %></td>
        <td><%= link_to 'Destroy', usertrip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User trip', new_usertrip_path %>

app/views/usertrips/new.html.erb
<h1>New User Trip</h1>

<%= render 'form' %>

<%= link_to 'Back', usertrips_path %>

app/views/usertrips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @usertrip.user_id %>
</p>

<p>
  <strong>Trip:</strong>
  <%= @usertrip.trip_id %>
</p>

<%= link_to 'Edit', edit_usertrip_path(@usertrip) %> |
<%= link_to 'Back', usertrips_path %>